services:
  _defaults:
    autowire: true
    autoconfigure: true

  alexlisenkov.uuid_argument_resolver_bundle.uuid_invalid_response:
    class: '@Psr\Http\Message\ResponseInterface'
    factory: [ 'AlexLisenkov\UuidArgumentResolverBundle\InvalidUuidResponseFactory', create ]

  AlexLisenkov\UuidArgumentResolverBundle\Resolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 150 }
    arguments:
      $httpFoundationFactory: 'Symfony\Bridge\PsrHttpMessage\HttpFoundationFactory'
      $invalidUuidResponse: '@alexlisenkov.uuid_argument_resolver_bundle.uuid_invalid_response'
